wordpress.lo: /home/dolphin/php-5.3.10/ext/wordpress/wordpress.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/dolphin/php-5.3.10/ext/wordpress $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/dolphin/php-5.3.10/ext/wordpress/wordpress.c -o wordpress.lo 
$(phplibdir)/wordpress.la: ./wordpress.la
	$(LIBTOOL) --mode=install cp ./wordpress.la $(phplibdir)

./wordpress.la: $(shared_objects_wordpress) $(WORDPRESS_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_wordpress) $(WORDPRESS_SHARED_LIBADD)

